--Scripts for security

drop table ejava.GROUP_TABLE;

CREATE TABLE EJAVA.GROUP_TABLE(
    GROUP_NAME varchar(50) NOT NULL,
    EMAIL varchar(100) NOT NULL,
    CONSTRAINT cpk_gp_usr PRIMARY KEY (GROUP_NAME,EMAIL)
);

ALTER TABLE EJAVA.GROUP_TABLE
	ADD FOREIGN KEY (EMAIL)
	REFERENCES EJAVA.BUBBLE_BOOK_USER (EMAIL)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT;


INSERT  INTO EJAVA.GROUP_TABLE(GROUP_NAME,EMAIL) VALUES
('USER','JR@NUS.EDU.SG'),('USER','vinc@NUS.EDU.SG'),
('USER','nags@NUS.EDU.SG'),('USER','aish@NUS.EDU.SG'),
('USER','npk@NUS.EDU.SG'),('ADMIN','barney@gmail.com'); 

